# utt data and 20% ted talk trained concurrently model test
# CUDA_VISIBLE_DEVICES=2 python src/test.py --pretrained-model=bert-base-uncased --lstm-dim=-1 --data-path=data/test/temp_test --weight-path=out/fullUtt_20%LJSpeech_defaultImpl_seed1 --sequence-length=256 --save-path=out/fullUtt_20%LJSpeech_defaultImpl_seed1 --sliding-window=False
# CUDA_VISIBLE_DEVICES=2 python src/test.py --pretrained-model=bert-base-multilingual-uncased --lstm-dim=-1 --data-path=data/test/temp_test --weight-path=out/fullUtt_20%LJSpeech_defaultImpl_seed1 --sequence-length=256 --save-path=out/fullUtt_tedTalkOriginal_defaultImpl_seed1 --sliding-window=False
# CUDA_VISIBLE_DEVICES=2 python src/test.py --pretrained-model=xlm-roberta-base --lstm-dim=-1 --data-path=data/test/temp_test --weight-path=out/fullUtt_20%LJSpeech_defaultImpl_seed1 --sequence-length=256 --save-path=out/fullUtt_20%LJSpeech_defaultImpl_seed1 --sliding-window=False
# # 
#
# utt data and 20% LJ Data trained concurrently model test
# CUDA_VISIBLE_DEVICES=2 python src/test.py --pretrained-model=bert-base-uncased --lstm-dim=-1 --data-path=data/test/temp_test --weight-path=out/fullUtt_20%LJSpeech_removeTokens_seed1 --sequence-length=256 --save-path=out/fullUtt_20%LJSpeech_removeTokens_seed1 --sliding-window=False
# CUDA_VISIBLE_DEVICES=2 python src/test.py --pretrained-model=bert-base-multilingual-uncased --lstm-dim=-1 --data-path=data/test/temp_test --weight-path=out/fullUtt_20%LJSpeech_removeTokens_seed1 --sequence-length=256 --save-path=out/fullUtt_20%LJSpeech_removeTokens_seed1 --sliding-window=False
# CUDA_VISIBLE_DEVICES=2 python src/test.py --pretrained-model=xlm-roberta-base --lstm-dim=-1 --data-path=data/test/temp_test --weight-path=out/fullUtt_20%LJSpeech_removeTokens_seed1 --sequence-length=256 --save-path=out/fullUtt_20%LJSpeech_removeTokens_seed1 --sliding-window=False
#
# CUDA_VISIBLE_DEVICES=1,2 python src/train.py --cuda=True --pretrained-model=bert-base-uncased --freeze-bert=False --lstm-dim=-1 --language=sr_restored_split_by_windowing --seed=1 --lr=5e-6 --epoch=20 --augment-type=all  --augment-rate=0.15 --alpha-sub=0.4 --alpha-del=0.4 --data-path=data --save-path=out/srRestoredSplit_windowing_triangleHalfTo1
# CUDA_VISIBLE_DEVICES=1,2 python src/train.py --cuda=True --pretrained-model=bert-base-uncased --freeze-bert=False --lstm-dim=-1 --language=sr_restored_split_by_windowing --seed=1 --lr=5e-6 --epoch=20 --augment-type=all  --augment-rate=0.15 --alpha-sub=0.4 --alpha-del=0.4 --data-path=data --sliding-window=False --save-path=out/srRestoredSplit_windowing_defaultImpl
# CUDA_VISIBLE_DEVICES=1,2 python src/train.py --cuda=True --pretrained-model=xlm-roberta-base --freeze-bert=False --lstm-dim=-1 --language=sr_restored_split_by_windowing --seed=1 --lr=5e-6 --epoch=20 --augment-type=all  --augment-rate=0.15 --alpha-sub=0.4 --alpha-del=0.4 --data-path=data --save-path=out/srRestoredSplit_windowing_triangleHalfTo1
# CUDA_VISIBLE_DEVICES=1,2 python src/train.py --cuda=True --pretrained-model=xlm-roberta-base --freeze-bert=False --lstm-dim=-1 --language=sr_restored_split_by_windowing --seed=1 --lr=5e-6 --epoch=20 --augment-type=all  --augment-rate=0.15 --alpha-sub=0.4 --alpha-del=0.4 --data-path=data --sliding-window=False --save-path=out/srRestoredSplit_windowing_defaultImpl
# CUDA_VISIBLE_DEVICES=1,2 python src/train.py --cuda=True --pretrained-model=bert-base-multilingual-uncased --freeze-bert=False --lstm-dim=-1 --language=sr_restored_split_by_windowing --seed=1 --lr=5e-6 --epoch=20 --augment-type=all  --augment-rate=0.15 --alpha-sub=0.4 --alpha-del=0.4 --data-path=data --save-path=out/srRestoredSplit_windowing_triangleHalfTo1
# CUDA_VISIBLE_DEVICES=1,2 python src/train.py --cuda=True --pretrained-model=bert-base-multilingual-uncased --freeze-bert=False --lstm-dim=-1 --language=sr_restored_split_by_windowing --seed=1 --lr=5e-6 --epoch=20 --augment-type=all  --augment-rate=0.15 --alpha-sub=0.4 --alpha-del=0.4 --data-path=data --sliding-window=False --save-path=out/srRestoredSplit_windowing_defaultImpl
CUDA_VISIBLE_DEVICES=2 python src/test.py --pretrained-model=bert-base-uncased --lstm-dim=-1 --data-path=data/utt_version2/test_version2 --weight-path=out/fullTedTalk_newUTT_triangleHalfTo1_seed1 --sequence-length=256 --save-path=out/fullTedTalk_newUTT_triangleHalfTo1_seed1
CUDA_VISIBLE_DEVICES=2 python src/test.py --pretrained-model=bert-base-multilingual-uncased --lstm-dim=-1 --data-path=data/utt_version2/test_version2 --weight-path=out/fullTedTalk_newUTT_triangleHalfTo1_seed1 --sequence-length=256 --save-path=out/fullTedTalk_newUTT_triangleHalfTo1_seed1
CUDA_VISIBLE_DEVICES=2 python src/test.py --pretrained-model=xlm-roberta-base --lstm-dim=-1 --data-path=data/utt_version2/test_version2 --weight-path=out/fullTedTalk_newUTT_triangleHalfTo1_seed1 --sequence-length=256 --save-path=out/fullTedTalk_newUTT_triangleHalfTo1_seed1
#
# utt and 20% mixed-LJ-speech trained concurrently (with lower case)
# CUDA_VISIBLE_DEVICES=1 python src/train.py --cuda=True --pretrained-model=bert-base-uncased --freeze-bert=False --lstm-dim=-1 --language=utt_with_LJ_speech --seed=1 --lr=5e-6 --epoch=10 --augment-type=all  --augment-rate=0.15 --alpha-sub=0.4 --alpha-del=0.4 --data-path=data --save-path=out/fullUtt_20%LJSpeech_triangle0To1_seed1
# CUDA_VISIBLE_DEVICES=1 python src/train.py --cuda=True --pretrained-model=bert-base-multilingual-uncased --freeze-bert=False --lstm-dim=-1 --language=utt_with_LJ_speech --seed=1 --lr=5e-6 --epoch=10 --augment-type=all  --augment-rate=0.15 --alpha-sub=0.4 --alpha-del=0.4 --data-path=data --save-path=out/fullUtt_20%LJSpeech_triangle0To1_seed1
# CUDA_VISIBLE_DEVICES=1 python src/train.py --cuda=True --pretrained-model=xlm-roberta-base --freeze-bert=False --lstm-dim=-1 --language=utt_with_LJ_speech --seed=1 --lr=5e-6 --epoch=10 --augment-type=all  --augment-rate=0.15 --alpha-sub=0.4 --alpha-del=0.4 --data-path=data --save-path=out/fullUtt_20%LJSpeech_triangle0To1_seed1
#
# utt data and 20% ted talk asr trained concurrently (with lower case)
# CUDA_VISIBLE_DEVICES=1,2 python src/train.py --cuda=True --pretrained-model=bert-base-uncased --freeze-bert=False --lstm-dim=-1 --language=utt_with_ted_talk_asr --seed=1 --lr=5e-6 --epoch=10 --augment-type=all  --augment-rate=0.15 --alpha-sub=0.4 --alpha-del=0.4 --data-path=data --save-path=out/fullUtt_tedTalkAsr_slidingWindow_seed1
# CUDA_VISIBLE_DEVICES=1,2 python src/train.py --cuda=True --pretrained-model=bert-base-multilingual-uncased --freeze-bert=False --lstm-dim=-1 --language=utt_with_ted_talk_asr --seed=1 --lr=5e-6 --epoch=10 --augment-type=all  --augment-rate=0.15 --alpha-sub=0.4 --alpha-del=0.4 --data-path=data --save-path=out/fullUtt_tedTalkAsr_slidingWindow_seed1
# CUDA_VISIBLE_DEVICES=1,2 python src/train.py --cuda=True --pretrained-model=xlm-roberta-base --freeze-bert=False --lstm-dim=-1 --language=utt_with_ted_talk_asr --seed=1 --lr=5e-6 --epoch=10 --augment-type=all  --augment-rate=0.15 --alpha-sub=0.4 --alpha-del=0.4 --data-path=data --save-path=out/fullUtt_tedTalkAsr_slidingWindow_seed1
# 
# test
# python src/train.py --cuda=True --pretrained-model=bert-base-uncased --freeze-bert=False --lstm-dim=-1 --language=test --sequence-length=20 --seed=1 --lr=5e-6 --epoch=10 --augment-type=all  --augment-rate=0 --alpha-sub=0.4 --alpha-del=0.4 --data-path=data --save-path=out/test --sliding-window=True
#
#for inference
# CUDA_VISIBLE_DEVICES=1,2 python src/train.py --cuda=True --pretrained-model=xlm-roberta-base --freeze-bert=False --lstm-dim=-1 --language=restore_sr_by_inference --seed=1 --lr=5e-6 --epoch=20 --augment-type=all  --augment-rate=0.15 --alpha-sub=0.4 --alpha-del=0.4 --data-path=data --save-path=out/restore_sr_by_inference_version2
# CUDA_VISIBLE_DEVICES=1 python src/inference.py --in-file='data/text_for_inference' --weight-path='out/restore_sr_by_inference_version2/xlm-roberta-base.pt' --out-file='data/text_restored_by_inference_version2' --pretrained-model=xlm-roberta-base